name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-response:
    runs-on: ubuntu-latest
    
    # Claudeがメンションされた場合のみ実行
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --production 2>/dev/null || echo "No package.json found, skipping npm install"

      - name: Claude Response
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # プロジェクト固有の設定
          claude_config_path: .claude/CLAUDE.md
          mcp_config_path: .claude/mcp_config.json
          
      - name: Post-processing
        if: success()
        run: |
          echo "✅ Claude has responded successfully"
          
      - name: Error handling
        if: failure()
        run: |
          echo "❌ Claude encountered an error"
          # エラーログの記録
          mkdir -p .claude/logs
          echo "[$(date)] Error in workflow run #${{ github.run_id }}" >> .claude/logs/errors.log

  # 自動テストとリンティング
  quality-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            npm ci
          else
            echo "No package.json found, skipping dependency installation"
          fi

      - name: Run linting
        run: |
          if [ -f "package.json" ] && grep -q "\"lint\"" package.json; then
            npm run lint
          else
            echo "No lint script found, skipping"
          fi

      - name: Run tests
        run: |
          if [ -f "package.json" ] && grep -q "\"test\"" package.json; then
            npm test
          else
            echo "No test script found, skipping"
          fi

      - name: Type checking
        run: |
          if [ -f "tsconfig.json" ]; then
            npx tsc --noEmit
          else
            echo "No TypeScript configuration found, skipping type check"
          fi